name: Deploy LD11 Dashboard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        cp index.php voters_api.php package.json deploy/
        cp -r public deploy/
        cp -r build deploy/
        
    - name: Deploy to HostGator via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /public_html/ld11/
          
    - name: Create and upload .htaccess file
      run: |
        echo "RewriteEngine On" > .htaccess
        echo "RewriteBase /ld11/" >> .htaccess
        echo "" >> .htaccess
        echo "# Handle React Router" >> .htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
        echo "RewriteCond %{REQUEST_FILENAME} !-d" >> .htaccess
        echo "RewriteRule . /ld11/index.html [L]" >> .htaccess
        echo "" >> .htaccess
        echo "# Security headers" >> .htaccess
        echo "Header always set X-Content-Type-Options nosniff" >> .htaccess
        echo "Header always set X-Frame-Options DENY" >> .htaccess
        echo "Header always set X-XSS-Protection \"1; mode=block\"" >> .htaccess
        
        # Copy .htaccess to deploy directory
        cp .htaccess deploy/
        
    - name: Upload .htaccess
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /public_html/ld11/
