name: Deploy to HostGator

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: List build files
      run: |
        echo "Build directory contents:"
        ls -la build/
        echo "Build static directory contents:"
        ls -la build/static/ || echo "No static directory"
        echo "Build index.html exists:"
        ls -la build/index.html || echo "No index.html found"
        
    - name: Deploy React build to HostGator via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: /sunbeltsolutions.org/ld11/
          
    - name: Upload PHP and HTML files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /sunbeltsolutions.org/ld11/
        include: |
          index.php
          index.html
          fixed-api.php
          voters_api.php
          .htaccess
          
    - name: Upload public assets
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: /sunbeltsolutions.org/ld11/public/